config/routes.rb
Geo::Application.routes.draw do

  get "aldeia_digital/index"

  get "aldeia_digital/show"

  get "pontos_onibus/index"

  get "pontos_onibus/show"

  get "pontos_onibus/_onibus"

  get "saudes/index"

  get "saudes/show"

  get "saudes/edit"

  get "saudes/_saudes"

  get "educacao/index"

  get "educacao/show"

  get "educacao/edit"

  resources :zoneamentos
  resources :bairros
  resources :ruas, :skip => :show

  match 'ruas/show/:id/:id_bairro' => 'ruas#show', :as => :ruas_show

  get "mapas/index"
  match 'mapas/show/:insc_base' => 'mapas#show'
  match 'mapas/detail/:id' => 'mapas#detail', :as => :mapas_detail

  devise_for :users, :path_prefix => 'geo'#, :skip => [:registrations, :sessions]

  resources :users do
    get 'logged', :on => :collection
  end
=begin

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
=end

  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/models/rua.rb
# -*- encoding : utf-8 -*-
class Rua < ActiveRecord::Base
  #attr_accessible :id_rua, :nome, :the_geom

  #self.rgeo_factory_generator = RGeo::Geos.factory_generator(:srid => 29193)
  self.table_name = "logradouros"
  self.primary_key = 'id'

	def self.search(search)

	    if search
	      where('nome LIKE ?' , "%#{search.upcase}%")
	      #find_by_sql("select * from ruas where nome like '#{search.upcase}%'")
	    else
	      scoped
	    end
	end

end

app/controllers/ruas_controller.rb
# -*- encoding : utf-8 -*-
class RuasController < ApplicationController
  # GET /ruas
  # GET /ruas.json
  load_and_authorize_resource
  def index

    nome = params[:search]

    if nome.present?
      @ruas = Rua.paginate_by_sql("SELECT b.id as id_bairro, b.nome as bairro, r.*
                        from logradouros r, bairros_oficial b
                        where r.nome like '%"+nome.upcase+"%' and
                        r.the_geom && b.the_geom and
                        st_intersects(r.the_geom, b.the_geom)", :page => params[:page], :per_page => 10)
    else
      @ruas.clear
    end


    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @ruas }
      format.json { render :json => @ruas }
    end
  end

  def detail
    @rua = Rua.find_by_sql("SELECT b.id as id_bairro, b.nome as bairro, r.*
                        from logradouros r, bairros_oficial b
                        where r.id = "+params[:id]+" and
                        b.id = "+params[:id_bairro]+" and
                        r.the_geom && b.the_geom and
                        st_intersects(r.the_geom, b.the_geom)")
  end




  # GET /ruas/1
  # GET /ruas/1.json
  def show
    #@@rua = Rua.find(params[:id])

    @rua = Rua.find_by_sql("SELECT b.id as id_bairro, b.nome as bairro, r.*, st_length(r.the_geom) as tamanho,
                        st_length(st_intersection(r.the_geom, b.the_geom))  as parcial
                        from logradouros r, bairros_oficial b
                        where r.id = "+params[:id]+" and
                        b.id = "+params[:id_bairro]+" and
                        r.the_geom && b.the_geom and
                        st_intersects(r.the_geom, b.the_geom)")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @rua }
    end
  end

  # GET /ruas/new
  # GET /ruas/new.json
  def new
    @rua = Rua.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @rua }
    end
  end

  # GET /ruas/1/edit
  def edit
    @rua = Rua.find(params[:id])
  end

  # POST /ruas
  # POST /ruas.json
  def create
    @rua = Rua.new(params[:rua])

    respond_to do |format|
      if @rua.save
        format.html { redirect_to @rua, :notice => 'Rua was successfully created.' }
        format.json { render :json => @rua, :status => :created, :location => @rua }
      else
        format.html { render :action => "new" }
        format.json { render :json => @rua.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ruas/1
  # PUT /ruas/1.json
  def update
    @rua = Rua.find(params[:id])

    respond_to do |format|
      if @rua.update_attributes(params[:rua])
        format.html { redirect_to @rua, :notice => 'Rua was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @rua.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ruas/1
  # DELETE /ruas/1.json
  def destroy
    @rua = Rua.find(params[:id])
    @rua.destroy

    respond_to do |format|
      format.html { redirect_to ruas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ruas_helper.rb
# -*- encoding : utf-8 -*-
module RuasHelper
end

app/views/ruas/_form.html.erb
<%= simple_form_for(@rua) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :id_rua %>
    <%= f.input :nome %>
    <%= f.input :the_geom %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ruas/_ruas.html.erb
<table class="table table-bordered table-hover table-condensed">
  <thead>
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Bairro</th>
    <th colspan=3 style="text-align: center;">Ações</th>
  </tr>
  </thead>
  <tbody>
    <% if @ruas.empty? %>
      <tr>
        <td colspan=4>Não exitem registros com o valor informado</td>
      </tr>
    <% end %>
    <% @ruas.each do |rua| %>
      <tr>
        <td><%= rua.id %></td>
        <td><%= rua.nome %></td>
        <td><%= rua.bairro %></td>

        <td style="text-align: center;"><%= link_to '', ruas_show_path(rua.id, rua.id_bairro), :class => 'icon-search', :title => 'Visualizar' %></td>
        <% if can? :update, rua %>
          <td style="text-align: center;"><%= link_to '', edit_rua_path(rua), :class => 'icon-pencil', :title => 'Editar' %></td>
            <% if can? :delete, Rua %>
            <td style="text-align: center;"><%= link_to '', rua, :class => 'icon-trash', :method => :delete, :data => { :confirm => 'Are you sure?' }, :title => 'Apagar' %></td>
            <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% unless @ruas.empty? %>
<%= will_paginate @ruas, :renderer => BootstrapPagination::Rails, :class => 'pagination pagination-centered' %>
<% end %>

app/views/ruas/_ruasBairro.html.erb
 <div id="ruas">
  <table class="table table-bordered table-hover table-condensed">
    <col width="5%">
    <col width="15%">
  <thead>
  <tr>
    <th>Id</th>
    <th>Tipo</th>
    <th>Nome</th>
    <th>Comprimento no bairro</th>
    <th>Comprimento total</th>
  </tr>
  </thead>
  <tbody>
    <% if @ruas.empty? %>
      <tr>
        <td colspan=4>Não exitem registros com o valor informado</td>
      </tr>
    <% end %>
    <% @ruas.each do |rua| %>
      <tr>
        <td><%= rua.id %></td>
        <td><%= rua.tipo_rua.humanize %></td>
        <td><%= rua.nome %></td>
        <td><%= rua.parcial.to_f.round(2) %> metros</td>
        <td><%= rua.total.to_f.round(2) %> metros</td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/ruas/edit.html.erb
<h1>Editing rua</h1>

<%= render 'form' %>

<%= link_to 'Show', @rua %> |
<%= link_to 'Back', ruas_path %>

app/views/ruas/index.html.erb
<h3>Lista de Logradouros</h3>

<% if can? :read, Rua %>
<%= form_tag ruas_path, :method => 'get', :class => 'form-search', :id => 'ruas_search' do %>
  <%= text_field_tag :search, params[:search], :class => 'input-medium search-query', :placeholder => 'Logradouro' %>
    <%= submit_tag "Consultar", :nome => nil, :class => 'btn btn-primary' %>
<% end %>
<% end %>

<div id="ruas">
  <%= render 'ruas' %>
</div>

<br />

app/views/ruas/new.html.erb
<h1>New rua</h1>

<%= render 'form' %>

<%= link_to 'Back', ruas_path %>

app/views/ruas/show.html.erb
<input type="hidden" id="id_rua" value="<%= @rua[0].id_rua %>" />
<h4>Informações:</h4>
<table class="table table-bordered table-hover table-condensed">
  <tbody>
      <tr>
        <td><b>Logradouro:</b></td>
        <td><%= @rua[0].nome %></td>
      </tr>
      <tr>
        <td><b>Bairro:</b></td>
        <td><%= @rua[0].bairro %></td>
      </tr>
      <tr>
        <td><b>Extensão no Bairro:</b></td>
        <td><%= @rua[0].parcial.to_f.round(2) %> metros</td>
      </tr>
       <tr>
        <td><b>Extensão Total:</b></td>
        <td><%= @rua[0].tamanho.to_f.round(2) %> metros</td>
      </tr>
  </tbody>
</table>
<div id="map"style="height: 400px;"></div>

<script src="http://maps.google.com/maps/api/js?v=3.2&sensor=false"></script>
<%= javascript_include_tag "application", "mapa/ruas" %>