config/routes.rb
Geo::Application.routes.draw do

  get "aldeia_digital/index"

  get "aldeia_digital/show"

  get "pontos_onibus/index"

  get "pontos_onibus/show"

  get "pontos_onibus/_onibus"

  get "saudes/index"

  get "saudes/show"

  get "saudes/edit"

  get "saudes/_saudes"

  get "educacao/index"

  get "educacao/show"

  get "educacao/edit"

  resources :zoneamentos
  resources :bairros
  resources :ruas, :skip => :show

  match 'ruas/show/:id/:id_bairro' => 'ruas#show', :as => :ruas_show

  get "mapas/index"
  match 'mapas/show/:insc_base' => 'mapas#show'
  match 'mapas/detail/:id' => 'mapas#detail', :as => :mapas_detail

  devise_for :users, :path_prefix => 'geo'#, :skip => [:registrations, :sessions]

  resources :users do
    get 'logged', :on => :collection
  end
=begin

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
=end

  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/models/zoneamento.rb
# -*- encoding : utf-8 -*-
class Zoneamento < ActiveRecord::Base
  #attr_accessible :atividade, :desc, :sigla

  #self.rgeo_factory_generator = RGeo::Geos.factory_generator(:srid => 29193)
  self.table_name = "zonas"
  self.primary_key = 'gid'


end

app/controllers/zoneamentos_controller.rb
# -*- encoding : utf-8 -*-
class ZoneamentosController < ApplicationController
  # GET /zoneamentos
  # GET /zoneamentos.json
  def index
    @zoneamentos = Zoneamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @zoneamentos }
    end
  end

  # GET /zoneamentos/1
  # GET /zoneamentos/1.json
  def show
    @zoneamento = Zoneamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @zoneamento }
    end
  end

  # GET /zoneamentos/new
  # GET /zoneamentos/new.json
  def new
    @zoneamento = Zoneamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @zoneamento }
    end
  end

  # GET /zoneamentos/1/edit
  def edit
    @zoneamento = Zoneamento.find(params[:id])
  end

  # POST /zoneamentos
  # POST /zoneamentos.json
  def create
    @zoneamento = Zoneamento.new(params[:zoneamento])

    respond_to do |format|
      if @zoneamento.save
        format.html { redirect_to @zoneamento, :notice => 'Zoneamento was successfully created.' }
        format.json { render :json => @zoneamento, :status => :created, :location => @zoneamento }
      else
        format.html { render :action => "new" }
        format.json { render :json => @zoneamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /zoneamentos/1
  # PUT /zoneamentos/1.json
  def update
    @zoneamento = Zoneamento.find(params[:id])

    respond_to do |format|
      if @zoneamento.update_attributes(params[:zoneamento])
        format.html { redirect_to @zoneamento, :notice => 'Zoneamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @zoneamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /zoneamentos/1
  # DELETE /zoneamentos/1.json
  def destroy
    @zoneamento = Zoneamento.find(params[:id])
    @zoneamento.destroy

    respond_to do |format|
      format.html { redirect_to zoneamentos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/zoneamentos_helper.rb
# -*- encoding : utf-8 -*-
module ZoneamentosHelper
end

app/views/zoneamentos/_form.html.erb
<%= simple_form_for(@zoneamento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :sigla %>
    <%= f.input :desc %>
    <%= f.input :atividade %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/zoneamentos/edit.html.erb
<h1>Editing zoneamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @zoneamento %> |
<%= link_to 'Back', zoneamentos_path %>

app/views/zoneamentos/index.html.erb
<h1>Listing zoneamentos</h1>

<table>
  <tr>
    <th>Sigla</th>
    <th>Desc</th>
    <th>Atividade</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zoneamentos.each do |zoneamento| %>
  <tr>
    <td><%= zoneamento.sigla %></td>
    <td><%= zoneamento.desc %></td>
    <td><%= zoneamento.atividade %></td>
    <td><%= link_to 'Show', zoneamento %></td>
    <td><%= link_to 'Edit', edit_zoneamento_path(zoneamento) %></td>
    <td><%= link_to 'Destroy', zoneamento, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zoneamento', new_zoneamento_path %>

app/views/zoneamentos/new.html.erb
<h1>New zoneamento</h1>

<%= render 'form' %>

<%= link_to 'Back', zoneamentos_path %>

app/views/zoneamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sigla:</b>
  <%= @zoneamento.sigla %>
</p>

<p>
  <b>Desc:</b>
  <%= @zoneamento.desc %>
</p>

<p>
  <b>Atividade:</b>
  <%= @zoneamento.atividade %>
</p>


<%= link_to 'Edit', edit_zoneamento_path(@zoneamento) %> |
<%= link_to 'Back', zoneamentos_path %>