config/routes.rb
Geo::Application.routes.draw do

  get "aldeia_digital/index"

  get "aldeia_digital/show"

  get "pontos_onibus/index"

  get "pontos_onibus/show"

  get "pontos_onibus/_onibus"

  get "saudes/index"

  get "saudes/show"

  get "saudes/edit"

  get "saudes/_saudes"

  get "educacao/index"

  get "educacao/show"

  get "educacao/edit"

  resources :zoneamentos
  resources :bairros
  resources :ruas, :skip => :show

  match 'ruas/show/:id/:id_bairro' => 'ruas#show', :as => :ruas_show

  get "mapas/index"
  match 'mapas/show/:insc_base' => 'mapas#show'
  match 'mapas/detail/:id' => 'mapas#detail', :as => :mapas_detail

  devise_for :users, :path_prefix => 'geo'#, :skip => [:registrations, :sessions]

  resources :users do
    get 'logged', :on => :collection
  end
=begin

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
=end

  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/models/ability.rb
# -*- encoding : utf-8 -*-
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    if user.role == "admin"
      can :manage, :all
    else
      can [:read, :update], User, :id => user.id
      can :read, Fazenda
      can :read, Rua
      can :read, Zoneamento
      can :read, Bairro
      can :read, Educacao
      can :read, Saude
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/aldeia_digital.rb
# -*- encoding : utf-8 -*-
class AldeiaDigital < ActiveRecord::Base
  #attr_accessible :id_rua, :nome, :the_geom

  #self.rgeo_factory_generator = RGeo::Geos.factory_generator(:srid => 29193)
  self.table_name = "aldeia_digital_oficial"
  self.primary_key = 'gid'


end

app/models/bairro.rb
# -*- encoding : utf-8 -*-
class Bairro < ActiveRecord::Base
	self.table_name = "bairros_oficial"
	self.primary_key = 'id'


	def self.search(search)

    if search
      where('nome LIKE ?', "%#{search.upcase}%")
    else
      scoped
    end
  end


end

app/models/educacao.rb
# -*- encoding : utf-8 -*-
class Educacao < ActiveRecord::Base
  #attr_accessible :id_rua, :nome, :the_geom

  #self.rgeo_factory_generator = RGeo::Geos.factory_generator(:srid => 29193)
  self.table_name = "educacao_municipal"
  self.primary_key = 'gid'

	def self.search(search)

	    if search
	      where('nome LIKE ?' , "%#{search.upcase}%")
	      #find_by_sql("select * from ruas where nome like '#{search.upcase}%'")
	    else
	      scoped
	    end
	end

end

app/models/fazenda.rb
# -*- encoding : utf-8 -*-
class Fazenda < AbstractConnection
  #attr_accessible :areaconstruida, :areadolote, :bairro, :bairrocorresp, :beneficio, :cep, :cepcorresp, :cidadecorresp, :codloteamento, :compl, :complcorresp, :conservacao, :cpfcgc, :dtcadastro, :dtconstrucao, :endcorresp, :fracaocal, :fracaoideal, :identlote, :identquadra, :insc_base, :inscricao, :localizimovel, :loteamento, :melhoria, :numero, :numerocorresp, :padrao, :proprietario, :responsavel, :situacao, :testada, :tipoimovel, :tipoobra, :tipoterreno, :uf
self.table_name = "sisimob.vw_busca_inscricao"
self.primary_key = 'inscricao'



  def self.search(search)

    if search
      where('proprietario LIKE ?', "#{search}%")
    else
      scoped
    end
  end



end

app/models/pontos_onibus.rb
# -*- encoding : utf-8 -*-
class PontosOnibus < ActiveRecord::Base
  #attr_accessible :id_rua, :nome, :the_geom

  #self.rgeo_factory_generator = RGeo::Geos.factory_generator(:srid => 29193)
  self.table_name = "ponto_onibus"
  self.primary_key = 'gid'


end

app/models/rua.rb
# -*- encoding : utf-8 -*-
class Rua < ActiveRecord::Base
  #attr_accessible :id_rua, :nome, :the_geom

  #self.rgeo_factory_generator = RGeo::Geos.factory_generator(:srid => 29193)
  self.table_name = "logradouros"
  self.primary_key = 'id'

	def self.search(search)

	    if search
	      where('nome LIKE ?' , "%#{search.upcase}%")
	      #find_by_sql("select * from ruas where nome like '#{search.upcase}%'")
	    else
	      scoped
	    end
	end

end

app/models/saude.rb
# -*- encoding : utf-8 -*-
class Saude < ActiveRecord::Base
  #attr_accessible :id_rua, :nome, :the_geom

  #self.rgeo_factory_generator = RGeo::Geos.factory_generator(:srid => 29193)
  self.table_name = "saude_municipal"
  self.primary_key = 'gid'

	def self.search(search)

	    if search
	      where('descricao LIKE ?' , "%#{search.upcase}%")
	      #find_by_sql("select * from ruas where nome like '#{search.upcase}%'")
	    else
	      scoped
	    end
	end

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :role, :active
  # attr_accessible :title, :body

  ROLES = %w[admin usuario]


   def self.search(search)
    
    if search
      where('name LIKE ?', "#{search}%")
    else
      scoped
    end
  end

  def active_for_authentication?
    active
  end

  def inactive_message
    "Desculpe, sua conta foi desativada."
  end

end

app/models/zoneamento.rb
# -*- encoding : utf-8 -*-
class Zoneamento < ActiveRecord::Base
  #attr_accessible :atividade, :desc, :sigla

  #self.rgeo_factory_generator = RGeo::Geos.factory_generator(:srid => 29193)
  self.table_name = "zonas"
  self.primary_key = 'gid'


end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/bairros_helper.rb
# -*- encoding : utf-8 -*-
module BairrosHelper
end

app/helpers/educacao_helper.rb
module EducacaoHelper
end

app/helpers/errors_helper.rb
# -*- encoding : utf-8 -*-
module ErrorsHelper
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/mapas_helper.rb
# -*- encoding : utf-8 -*-
module MapasHelper
end

app/helpers/ruas_helper.rb
# -*- encoding : utf-8 -*-
module RuasHelper
end

app/helpers/saudes_helper.rb
module SaudesHelper
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/helpers/zoneamentos_helper.rb
# -*- encoding : utf-8 -*-
module ZoneamentosHelper
end

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
<div class="navbar navbar-fluid-top navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Sistema de Consultas Georeferenciadas", root_path, :class => 'brand' %>
      <div class="container-fluid nav-collapse">
        <!-- Devise -->

        <p class="navbar-text pull-right">

          Usuario: <%= link_to current_user.name, edit_user_registration_path,:class => 'navbar-link' %>
          <!--%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %-->

            <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'navbar-link', :style => 'padding-left:30px'  %>

      </p>


      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "EPD-Geoprocessamento" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

     <!-- CLASSE QUE DEFINE O CONTAINER COMO FLUIDO (100%) -->
    <div id="content" class="container-fluid">
        <!-- CLASSE PARA DEFINIR UMA LINHA -->
        <div class="row-fluid">
            <!-- COLUNA OCUPANDO 2 ESPAÇOS NO GRID -->
            <%= render 'layouts/navigation' %>
          <% if user_signed_in? %>
            <div class="span2">

              <div class="nav-fixed">
                <h4>Menu</h4>
                 <ul class="nav nav-tabs nav-stacked">
                    <li><%= link_to "Principal", root_url %></li>
                    <li><%= link_to "Consulta Inscrição", mapas_index_path %></li>
                    <li><%= link_to "Bairros", bairros_path %></li>
                    <li><%= link_to "Logradouros", ruas_path %></li>
                    <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                  </ul>


                   <% if current_user.role == "admin" %>
                      <h4>Administração</h4>
                         <ul class="nav nav-tabs nav-stacked">
                            <li><%= link_to "Gerenciar Usuarios", users_path %></li>
                            <li><%= link_to "Usuários Logados", logged_users_path %></li>
                          </ul>
                  <% end %>

              </div>
            </div>
            <!-- COLUNA OCUPANDO 10 ESPAÇOS NO GRID -->
            <div class="span9">
                <% if user_signed_in? %>
                  <%= bootstrap_flash %>
                <% end %>
             <%= yield %>
            </div>
        </div>

          <% end %>
          <% unless user_signed_in? %>
        <%= yield %>
        <% end %>
    </div>


      <footer class="container navbar navbar-fixed-top">
        <p>&copy; EPD-Geoprocessamento <%= Time.now.year %></p>
      </footer>

    </div>

    <%= javascript_include_tag "application" %>

  </body>
</html>