config/routes.rb
Geo::Application.routes.draw do

  get "aldeia_digital/index"

  get "aldeia_digital/show"

  get "pontos_onibus/index"

  get "pontos_onibus/show"

  get "pontos_onibus/_onibus"

  get "saudes/index"

  get "saudes/show"

  get "saudes/edit"

  get "saudes/_saudes"

  get "educacao/index"

  get "educacao/show"

  get "educacao/edit"

  resources :zoneamentos
  resources :bairros
  resources :ruas, :skip => :show

  match 'ruas/show/:id/:id_bairro' => 'ruas#show', :as => :ruas_show

  get "mapas/index"
  match 'mapas/show/:insc_base' => 'mapas#show'
  match 'mapas/detail/:id' => 'mapas#detail', :as => :mapas_detail

  devise_for :users, :path_prefix => 'geo'#, :skip => [:registrations, :sessions]

  resources :users do
    get 'logged', :on => :collection
  end
=begin

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
=end

  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/models/bairro.rb
# -*- encoding : utf-8 -*-
class Bairro < ActiveRecord::Base
	self.table_name = "bairros_oficial"
	self.primary_key = 'id'


	def self.search(search)

    if search
      where('nome LIKE ?', "%#{search.upcase}%")
    else
      scoped
    end
  end


end

app/controllers/bairros_controller.rb
# -*- encoding : utf-8 -*-
class BairrosController < ApplicationController
  # GET /bairros
  # GET /bairros.json

  load_and_authorize_resource

  def index
    @bairros = Bairro.accessible_by(current_ability).paginate_by_sql(
      "select st_area(b.the_geom)/1000 as area, b.* from bairros_oficial b where b.nome like '%"+params[:search].to_s.upcase+"%' order by b.nome", :page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bairros, :except => :the_geom}
      format.xml { render :xml => @bairros, :except => :the_geom }

    end
  end

  # GET /bairros/1
  # GET /bairros/1.json
  def show

    @bairro = Bairro.find_by_sql(
      "select st_area(b.the_geom)/1000 as area, b.* from bairros_oficial b where id ="+params[:id]+" order by b.nome")
    @ruas = Rua.find_by_sql("select r.*, st_length(st_intersection(r.the_geom, b.the_geom)) as parcial, st_length(r.the_geom) as total from logradouros r, bairros_oficial b
              where r.the_geom && b.the_geom and
              st_intersects(r.the_geom, b.the_geom) and
              not id_rua = 0 and
              b.id = "+params[:id]+" order by r.nome")

    @educacaos = Educacao.find_by_sql("select e.* from educacao_municipal e, bairros_oficial b
                  where e.the_geom && b.the_geom and
                  st_intersects(e.the_geom, b.the_geom) and
                  b.id = "+params[:id]+" order by e.nome")

    @saudes = Saude.find_by_sql("select e.* from saude_municipal e, bairros_oficial b
                  where e.the_geom && b.the_geom and
                  st_intersects(e.the_geom, b.the_geom) and
                  b.id = "+params[:id]+" order by e.descricao")

    @pontosOnibus = PontosOnibus.find_by_sql("select e.* from ponto_onibus e, bairros_oficial b
                  where e.the_geom && b.the_geom and
                  st_intersects(e.the_geom, b.the_geom) and
                  b.id = "+params[:id]+" order by e.gid")
    @antenas = AldeiaDigital.find_by_sql("select e.* from aldeia_digital_oficial e, bairros_oficial b
                  where e.the_geom && b.the_geom and
                  st_intersects(e.the_geom, b.the_geom) and
                  b.id = "+params[:id]+" order by e.gid")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => [@bairro, @ruas, @educacaos, @saudes], :except => :the_geom }
      format.xml { render :xml => [@bairro, @ruas, @educacaos, @saudes] ,:except => :the_geom}
    end
  end

  # GET /bairros/new
  # GET /bairros/new.json
  def new
    @bairro = Bairro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @bairro }
    end
  end

  # GET /bairros/1/edit
  def edit
    @bairro = Bairro.find(params[:id])
  end

  # POST /bairros
  # POST /bairros.json
  def create
    @bairro = Bairro.new(params[:bairro])

    respond_to do |format|
      if @bairro.save
        format.html { redirect_to @bairro, :notice => 'Bairro was successfully created.' }
        format.json { render :json => @bairro, :status => :created, :location => @bairro }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bairro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bairros/1
  # PUT /bairros/1.json
  def update
    @bairro = Bairro.find(params[:id])

    respond_to do |format|
      if @bairro.update_attributes(params[:bairro])
        format.html { redirect_to @bairro, :notice => 'Bairro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bairro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bairros/1
  # DELETE /bairros/1.json
  def destroy
    @bairro = Bairro.find(params[:id])
    @bairro.destroy

    respond_to do |format|
      format.html { redirect_to bairros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bairros_helper.rb
# -*- encoding : utf-8 -*-
module BairrosHelper
end

app/views/bairros/_bairros.html.erb
<table class="table table-bordered table-hover table-condensed">
  <thead>
  <tr>
    <th>Nome</th>
    <th>Doc. Regularização</th>
    <th>Pop. Masc (IBGE/2010)</th>
    <th>Pop. Fem (IBGE/2010)</th>
    <th>Pop. Total</th>
    <th>Área</th>
    <th colspan=3 style="text-align: center;">Ações</th>
  </tr>
  </thead>
  <tbody>
    <% @bairros.each do |bairro| %>
      <tr>
        <td><%= bairro.nome %></td>
        <td><%= bairro.doc_reg_nomen_bairro %></td>
        <td><%= bairro.pop_masc %></td>
        <td><%= bairro.pop_fem %></td>
        <td><%= bairro.pop_fem.to_i + bairro.pop_masc.to_i %></td>
        <td style="text-align: right;"><%= number_with_precision(bairro.area, :precision => 2, :separator => ',', :delimiter => '.') %> Km2</td>
        <td style="text-align: center;"><%= link_to '', bairro, :class => 'icon-search', :title => 'Visualizar' %></td>
        <% if can? :update, bairro %>
          <td style="text-align: center;"><%= link_to '', edit_bairro_path(bairro), :class => 'icon-pencil', :title => 'Editar' %></td>
            <% if can? :delete, bairro %>
            <td style="text-align: center;"><%= link_to '', bairro, :class => 'icon-trash', :method => :delete, :data => { :confirm => 'Are you sure?' }, :title => 'Apagar' %></td>
            <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<%= will_paginate @bairros, :renderer => BootstrapPagination::Rails, :class => 'pagination pagination-centered' %>

app/views/bairros/_detail.html.erb
<table class="table table-bordered table-hover table-condensed">
  <col width="30%">
  <tbody>
      <tr>
        <td><b>Nome:</b></td>
        <td><%= @bairro[0].nome %></td>
      </tr>
       <tr>
        <td><b>Doc. Regularização:</b></td>
        <td><%= @bairro[0].doc_reg_nomen_bairro %></td>
      </tr>
      <tr>
        <td><b>Pop. Masc (Censo IBGE/2010):</b></td>
        <td><%= @bairro[0].pop_masc %></td>
      </tr>
      <tr>
        <td><b>Pop. Fem (Censo IBGE/2010):</b></td>
        <td><%= @bairro[0].pop_fem %></td>
      </tr>
       <tr>
        <td><b>Pop. Total:</b></td>
        <td><%= @bairro[0].pop_fem.to_i + @bairro[0].pop_masc.to_i %></td>
      </tr>
      <tr>
        <td><b>Área:</b></td>
        <td><%= @bairro[0].area.to_f.round(2) %> Km2</td>
      </tr>

  </tbody>
</table>

app/views/bairros/_form.html.erb
<%= simple_form_for(@bairro) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :popmasc %>
    <%= f.input :popfem %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bairros/edit.html.erb
<h1>Editing bairro</h1>

<%= render 'form' %>

<%= link_to 'Show', @bairro %> |
<%= link_to 'Back', bairros_path %>

app/views/bairros/index.html.erb
<h3>Lista de Bairros</h3>

<% if can? :read, Bairro %>
<%= form_tag bairros_path, :method => 'get', :class => 'form-search', :id => 'bairros_search' do %>
  <%= text_field_tag :search, params[:search], :class => 'input-medium search-query' %>
    <%= submit_tag "Consultar", :bairro => nil, :class => 'btn btn-primary' %>
<% end %>
<% end %>

<div id="bairros">
  <%= render 'bairros' %>
</div>

<br />

app/views/bairros/new.html.erb
<h1>New bairro</h1>

<%= render 'form' %>

<%= link_to 'Back', bairros_path %>

app/views/bairros/show.html.erb
<h4>Informações:</h4>
<div>
<%= render "bairros/detail" %>
</div>

<h4>Estatísticas no Bairro:</h4>
<div class="accordion" id="accordion2">
<input type="hidden" id="id_bairro" value="<%= @bairro[0].id %>" />


  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Logradouros (Total: <%= @ruas.size %> )
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <%= render "ruas/ruasBairro" %>
      </div>
    </div>
  </div>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
        Saude  (Total: <%= @saudes.size %> )
      </a>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
      <div class="accordion-inner">
        <%= render "saudes/saudes" %>

      </div>
    </div>
  </div>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
        Educação  (Total: <%= @educacaos.size %> )
      </a>
    </div>
    <div id="collapseThree" class="accordion-body collapse">
      <div class="accordion-inner">
        <%= render "educacao/educacao" %>

      </div>
    </div>
  </div>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
        Pontos de Ônibus  (Total: <%= @pontosOnibus.size %> )
      </a>
    </div>
    <div id="collapseFour" class="accordion-body collapse">
      <div class="accordion-inner">
        <%= render "pontos_onibus/onibus" %>
      </div>
    </div>
  </div>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFive">
        Antenas Aldeia Digital  (Total: <%= @antenas.size %> )
      </a>
    </div>
    <div id="collapseFive" class="accordion-body collapse">
      <div class="accordion-inner">
        <%= render "aldeia_digital/antenas" %>
      </div>
    </div>
  </div>

</div>